/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_zhy_blogcodes_jni_complicated_MaybeUtils */

#ifndef _Included_com_zhy_blogcodes_jni_complicated_MaybeUtils
#define _Included_com_zhy_blogcodes_jni_complicated_MaybeUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_zhy_blogcodes_jni_complicated_MaybeUtils
 * Method:    generate
 * Signature: ()Lcom/zhy/blogcodes/jni/complicated/MaybeUtils;
 */
JNIEXPORT jobject JNICALL Java_com_zhy_blogcodes_jni_complicated_MaybeUtils_generate
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
