/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_zhy_blogcodes_jni_JniTest */

#ifndef _Included_com_zhy_blogcodes_jni_JniTest
#define _Included_com_zhy_blogcodes_jni_JniTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_zhy_blogcodes_jni_JniTest
 * Method:    welcome
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_zhy_blogcodes_jni_JniTest_welcome
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
